### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by ereichl42** [ereichl42/ODA-Pisa#11]

**Comment by Tobikay1896** [comment]
Timetable (Roadmap with Milestones)
Specification (Lastenheft)
Project Documentation

Description of SoftwareProject from Hochschule Hannover for recognition of modules from an alternative academic institution since Tobias Küster is an incoming group member:
Die in den Informatik-Modulen erworbenen Kenntnisse werden in Projekten
angewandt. Dabei werden wichtige Phasen des Softwareentwicklungsprozesses
durchlaufen (z.B. Anforderungsanalyse, Entwurf, Implementierung, Test und
Dokumentation). Die konkrete Durchführung erfolgt in Gruppenarbeit. Die
Studierenden sind in der Lage, das Projekt zu planen, durchzuführen und nach
erfolgreichem Abschluss die Ergebnisse zu präsentieren.
Inhalt • Einarbeitung in ausgewählte wissenschaftliche Themen aus dem Gebiet
Informatik/Maschinenbau
• Erstellung eines Pflichtenhefts auf Basis der Vorgaben eines fiktiven „Kunden“,
• Entwurf, Implementierung, Test und Dokumentation im Team
• Nutzung von Softwareplanungs-, und Versionsverwaltungssoftware
• Präsentation von Ergebnissen und Zwischenergebnissen
